import { createContext, useContext, useState, useEffect } from "react";

export const LANGUAGES = [
  // Balkan
  { code: "bs", label: "Bosanski",   flag: "🇧🇦" },
  { code: "sr", label: "Srpski",     flag: "🇷🇸" },
  { code: "hr", label: "Hrvatski",   flag: "🇭🇷" },
  { code: "sq", label: "Shqip",      flag: "🇦🇱" },
  { code: "sl", label: "Slovenščina",flag: "🇸🇮" },
  { code: "mk", label: "Македонски", flag: "🇲🇰" },
  // Zapadna Europa
  { code: "en", label: "English",    flag: "🇬🇧" },
  { code: "de", label: "Deutsch",    flag: "🇩🇪" },
  { code: "fr", label: "Français",   flag: "🇫🇷" },
  { code: "es", label: "Español",    flag: "🇪🇸" },
  { code: "it", label: "Italiano",   flag: "🇮🇹" },
  { code: "pt", label: "Português",  flag: "🇵🇹" },
  { code: "nl", label: "Nederlands", flag: "🇳🇱" },
  { code: "el", label: "Ελληνικά",   flag: "🇬🇷" },
  // Skandinavija
  { code: "sv", label: "Svenska",    flag: "🇸🇪" },
  { code: "no", label: "Norsk",      flag: "🇳🇴" },
  { code: "da", label: "Dansk",      flag: "🇩🇰" },
  { code: "fi", label: "Suomi",      flag: "🇫🇮" },
  // Srednja Europa
  { code: "pl", label: "Polski",     flag: "🇵🇱" },
  { code: "cs", label: "Čeština",    flag: "🇨🇿" },
  { code: "sk", label: "Slovenčina", flag: "🇸🇰" },
  { code: "hu", label: "Magyar",     flag: "🇭🇺" },
  { code: "ro", label: "Română",     flag: "🇷🇴" },
  { code: "bg", label: "Български",  flag: "🇧🇬" },
  // Istok
  { code: "ru", label: "Русский",    flag: "🇷🇺" },
  { code: "uk", label: "Українська", flag: "🇺🇦" },
  { code: "tr", label: "Türkçe",     flag: "🇹🇷" },
  // Srednji istok & Azija
  { code: "ar", label: "العربية",    flag: "🇸🇦" },
  { code: "he", label: "עברית",      flag: "🇮🇱" },
  { code: "fa", label: "فارسی",      flag: "🇮🇷" },
  // Azija
  { code: "zh", label: "中文",        flag: "🇨🇳" },
  { code: "ja", label: "日本語",      flag: "🇯🇵" },
  { code: "ko", label: "한국어",      flag: "🇰🇷" },
  { code: "hi", label: "हिन्दी",     flag: "🇮🇳" },
];

const TRANSLATIONS = {
  // svaki jezik ima i UI strings za unutar modova
  bs: { translate:"PREVEDI", transcribe:"TRANSKRIPCIJA", speak:"GOVORI", notes:"BILJEŠKE", meeting:"MEETING", school:"ŠKOLA", convo:"RAZGOVOR", reminders:"PODSJETNIK", settings:"Postavke", lang_pick:"Odaberi jezik",
    rec_lang:"Jezik snimanja", subject:"Predmet", start_rec:"POČNI SNIMANJE", stop_rec:"ZAUSTAVI SNIMANJE", cont_rec:"NASTAVI SNIMANJE", recording:"● Snimam...", analyze:"Analiziraj", copy:"Kopiraj", copied:"Kopirano!", export:"Export", ai_summary:"AI Sažetak", analyzing:"Analiziram...", select_lang:"Odaberi jezik i pritisni dugme", transcript_lbl:"Transkript", press_start:"Pritisni da počneš", no_reminder:"Nema podsjetnika. Dodaj prvi gore!", what_todo:"Šta treba da uradiš?", text_mode:"Tekst", voice_mode:"Glas", rec_voice:"Snimi glasovnu poruku", stop_voice:"Zaustavi", person_a:"Osoba A", person_b:"Osoba B", speak_a:"GOVORI A", speak_b:"GOVORI B", stop_translate:"ZAUSTAVI I PREVEDI", translating:"Prevodim...", select_langs:"Odaberi jezike i pritisni dugme ispod", trial_banner:"✦ Besplatno još", days:"dana", day:"dan" },
  sr: { translate:"PREVEDI", transcribe:"TRANSKRIPCIJA", speak:"GOVORI", notes:"BELEŠKE", meeting:"MEETING", school:"ŠKOLA", convo:"RAZGOVOR", reminders:"PODSJETNIK", settings:"Podešavanja", lang_pick:"Odaberi jezik",
    rec_lang:"Jezik snimanja", subject:"Predmet", start_rec:"POČNI SNIMANJE", stop_rec:"ZAUSTAVI SNIMANJE", cont_rec:"NASTAVI SNIMANJE", recording:"● Snimam...", analyze:"Analiziraj", copy:"Kopiraj", copied:"Kopirano!", export:"Export", ai_summary:"AI Sažetak", analyzing:"Analiziram...", select_lang:"Odaberi jezik i pritisni dugme", transcript_lbl:"Transkript", press_start:"Pritisni da počneš", no_reminder:"Nema podsetnika. Dodaj prvi gore!", what_todo:"Šta treba da uradiš?", text_mode:"Tekst", voice_mode:"Glas", rec_voice:"Snimi glasovnu poruku", stop_voice:"Zaustavi", person_a:"Osoba A", person_b:"Osoba B", speak_a:"GOVORI A", speak_b:"GOVORI B", stop_translate:"ZAUSTAVI I PREVEDI", translating:"Prevodim...", select_langs:"Odaberi jezike i pritisni dugme ispod", trial_banner:"✦ Besplatno još", days:"dana", day:"dan" },
  hr: { translate:"PREVEDI", transcribe:"TRANSKRIPCIJA", speak:"GOVORI", notes:"BILJEŠKE", meeting:"MEETING", school:"ŠKOLA", convo:"RAZGOVOR", reminders:"PODSJETNIK", settings:"Postavke", lang_pick:"Odaberi jezik",
    rec_lang:"Jezik snimanja", subject:"Predmet", start_rec:"POČNI SNIMANJE", stop_rec:"ZAUSTAVI SNIMANJE", cont_rec:"NASTAVI SNIMANJE", recording:"● Snimam...", analyze:"Analiziraj", copy:"Kopiraj", copied:"Kopirano!", export:"Export", ai_summary:"AI Sažetak", analyzing:"Analiziram...", select_lang:"Odaberi jezik i pritisni dugme", transcript_lbl:"Transkript", press_start:"Pritisni za početak", no_reminder:"Nema podsjetnika. Dodaj prvi gore!", what_todo:"Što treba napraviti?", text_mode:"Tekst", voice_mode:"Glas", rec_voice:"Snimi glasovnu poruku", stop_voice:"Zaustavi", person_a:"Osoba A", person_b:"Osoba B", speak_a:"GOVORI A", speak_b:"GOVORI B", stop_translate:"ZAUSTAVI I PREVEDI", translating:"Prevodim...", select_langs:"Odaberi jezike i pritisni dugme ispod", trial_banner:"✦ Besplatno još", days:"dana", day:"dan" },
  sq: { translate:"PËRKTHE", transcribe:"TRANSKRIPT", speak:"FOLI", notes:"SHËNIME", meeting:"TAKIM", school:"SHKOLLË", convo:"BISEDË", reminders:"KUJTUES", settings:"Cilësime", lang_pick:"Zgjidh gjuhën",
    rec_lang:"Gjuha e regjistrimit", subject:"Lënda", start_rec:"FILLO REGJISTRIMIN", stop_rec:"NDALO REGJISTRIMIN", cont_rec:"VAZHDO", recording:"● Duke regjistruar...", analyze:"Analizoje", copy:"Kopjo", copied:"Kopjuar!", export:"Eksporto", ai_summary:"Përmbledhje AI", analyzing:"Duke analizuar...", select_lang:"Zgjidh gjuhën dhe shtyp butonin", transcript_lbl:"Transkript", press_start:"Shtyp për të filluar", no_reminder:"Nuk ka kujtues. Shto të parin!", what_todo:"Çfarë duhet bërë?", text_mode:"Tekst", voice_mode:"Zë", rec_voice:"Regjistro mesazh zanor", stop_voice:"Ndalo", person_a:"Personi A", person_b:"Personi B", speak_a:"FOLI A", speak_b:"FOLI B", stop_translate:"NDALO DHE PËRKTHE", translating:"Duke përkthyer...", select_langs:"Zgjidh gjuhët dhe shtyp butonin poshtë", trial_banner:"✦ Falas edhe", days:"ditë", day:"ditë" },
  sl: { translate:"PREVEDI", transcribe:"TRANSKRIPCIJA", speak:"GOVORI", notes:"BELEŽKE", meeting:"SESTANEK", school:"ŠOLA", convo:"POGOVOR", reminders:"OPOMNIK", settings:"Nastavitve", lang_pick:"Izberi jezik",
    rec_lang:"Jezik snemanja", subject:"Predmet", start_rec:"ZAČNI SNEMANJE", stop_rec:"USTAVI SNEMANJE", cont_rec:"NADALJUJ", recording:"● Snemalm...", analyze:"Analiziraj", copy:"Kopiraj", copied:"Kopirano!", export:"Izvozi", ai_summary:"AI Povzetek", analyzing:"Analiziram...", select_lang:"Izberi jezik in pritisni gumb", transcript_lbl:"Transkript", press_start:"Pritisni za začetek", no_reminder:"Ni opomnikov. Dodaj prvega!", what_todo:"Kaj je treba narediti?", text_mode:"Besedilo", voice_mode:"Glas", rec_voice:"Posnimi glasovno sporočilo", stop_voice:"Ustavi", person_a:"Oseba A", person_b:"Oseba B", speak_a:"GOVORI A", speak_b:"GOVORI B", stop_translate:"USTAVI IN PREVEDI", translating:"Prevajam...", select_langs:"Izberi jezike in pritisni gumb spodaj", trial_banner:"✦ Brezplačno še", days:"dni", day:"dan" },
  mk: { translate:"ПРЕВЕДИ", transcribe:"ТРАНСКРИПТ", speak:"ЗБОРУВАЈ", notes:"БЕЛЕШКИ", meeting:"СОСТАНОК", school:"УЧИЛИШТЕ", convo:"РАЗГОВОР", reminders:"ПОТСЕТНИК", settings:"Поставки", lang_pick:"Одбери јазик",
    rec_lang:"Јазик на снимање", subject:"Предмет", start_rec:"ПОЧНИ СНИМАЊЕ", stop_rec:"ЗАПРИ СНИМАЊЕ", cont_rec:"ПРОДОЛЖИ", recording:"● Снимам...", analyze:"Анализирај", copy:"Копирај", copied:"Копирано!", export:"Извези", ai_summary:"AI Резиме", analyzing:"Анализирам...", select_lang:"Одбери јазик и притисни копче", transcript_lbl:"Транскрипт", press_start:"Притисни за почеток", no_reminder:"Нема потсетници. Додај прв!", what_todo:"Што треба да се направи?", text_mode:"Текст", voice_mode:"Глас", rec_voice:"Сними гласовна порака", stop_voice:"Запри", person_a:"Лице А", person_b:"Лице Б", speak_a:"ЗБОРУВАЈ А", speak_b:"ЗБОРУВАЈ Б", stop_translate:"ЗАПРИ И ПРЕВЕДИ", translating:"Преведувам...", select_langs:"Одбери јазици и притисни копче подолу", trial_banner:"✦ Бесплатно уште", days:"дена", day:"ден" },
  en: { translate:"TRANSLATE", transcribe:"TRANSCRIBE", speak:"SPEAK", notes:"NOTES", meeting:"MEETING", school:"SCHOOL", convo:"CONVO", reminders:"REMIND", settings:"Settings", lang_pick:"Pick language",
    rec_lang:"Recording language", subject:"Subject", start_rec:"START RECORDING", stop_rec:"STOP RECORDING", cont_rec:"CONTINUE", recording:"● Recording...", analyze:"Analyze", copy:"Copy", copied:"Copied!", export:"Export", ai_summary:"AI Summary", analyzing:"Analyzing...", select_lang:"Select language and press record", transcript_lbl:"Transcript", press_start:"Press to start", no_reminder:"No reminders. Add your first!", what_todo:"What needs to be done?", text_mode:"Text", voice_mode:"Voice", rec_voice:"Record voice message", stop_voice:"Stop", person_a:"Person A", person_b:"Person B", speak_a:"SPEAK A", speak_b:"SPEAK B", stop_translate:"STOP & TRANSLATE", translating:"Translating...", select_langs:"Select languages and press button below", trial_banner:"✦ Free for", days:"days", day:"day" },
  de: { translate:"ÜBERSETZEN", transcribe:"TRANSKRIPT", speak:"SPRECHEN", notes:"NOTIZEN", meeting:"MEETING", school:"SCHULE", convo:"GESPRÄCH", reminders:"ERINNERN", settings:"Einstellungen", lang_pick:"Sprache wählen",
    rec_lang:"Aufnahmesprache", subject:"Fach", start_rec:"AUFNAHME STARTEN", stop_rec:"AUFNAHME STOPPEN", cont_rec:"WEITER", recording:"● Aufnahme...", analyze:"Analysieren", copy:"Kopieren", copied:"Kopiert!", export:"Exportieren", ai_summary:"KI-Zusammenfassung", analyzing:"Analysiere...", select_lang:"Sprache wählen und aufnehmen", transcript_lbl:"Transkript", press_start:"Drücken zum Starten", no_reminder:"Keine Erinnerungen. Erste hinzufügen!", what_todo:"Was muss getan werden?", text_mode:"Text", voice_mode:"Sprache", rec_voice:"Sprachnachricht aufnehmen", stop_voice:"Stoppen", person_a:"Person A", person_b:"Person B", speak_a:"SPRECHEN A", speak_b:"SPRECHEN B", stop_translate:"STOPPEN & ÜBERSETZEN", translating:"Übersetze...", select_langs:"Sprachen wählen und Taste drücken", trial_banner:"✦ Kostenlos noch", days:"Tage", day:"Tag" },
  fr: { translate:"TRADUIRE", transcribe:"TRANSCRIRE", speak:"PARLER", notes:"NOTES", meeting:"RÉUNION", school:"ÉCOLE", convo:"CONVO", reminders:"RAPPELS", settings:"Paramètres", lang_pick:"Choisir langue",
    rec_lang:"Langue d'enregistrement", subject:"Matière", start_rec:"DÉMARRER L'ENREGISTREMENT", stop_rec:"ARRÊTER", cont_rec:"CONTINUER", recording:"● Enregistrement...", analyze:"Analyser", copy:"Copier", copied:"Copié!", export:"Exporter", ai_summary:"Résumé IA", analyzing:"Analyse en cours...", select_lang:"Choisir la langue et enregistrer", transcript_lbl:"Transcription", press_start:"Appuyer pour commencer", no_reminder:"Aucun rappel. Ajoutez le premier!", what_todo:"Que faut-il faire?", text_mode:"Texte", voice_mode:"Voix", rec_voice:"Enregistrer message vocal", stop_voice:"Arrêter", person_a:"Personne A", person_b:"Personne B", speak_a:"PARLER A", speak_b:"PARLER B", stop_translate:"ARRÊTER & TRADUIRE", translating:"Traduction...", select_langs:"Choisir les langues et appuyer", trial_banner:"✦ Gratuit encore", days:"jours", day:"jour" },
  es: { translate:"TRADUCIR", transcribe:"TRANSCRIBIR", speak:"HABLAR", notes:"NOTAS", meeting:"REUNIÓN", school:"ESCUELA", convo:"CONVO", reminders:"RECORDAR", settings:"Ajustes", lang_pick:"Elegir idioma",
    rec_lang:"Idioma de grabación", subject:"Materia", start_rec:"INICIAR GRABACIÓN", stop_rec:"DETENER GRABACIÓN", cont_rec:"CONTINUAR", recording:"● Grabando...", analyze:"Analizar", copy:"Copiar", copied:"¡Copiado!", export:"Exportar", ai_summary:"Resumen IA", analyzing:"Analizando...", select_lang:"Seleccionar idioma y grabar", transcript_lbl:"Transcripción", press_start:"Pulsar para empezar", no_reminder:"Sin recordatorios. ¡Agrega el primero!", what_todo:"¿Qué hay que hacer?", text_mode:"Texto", voice_mode:"Voz", rec_voice:"Grabar mensaje de voz", stop_voice:"Detener", person_a:"Persona A", person_b:"Persona B", speak_a:"HABLAR A", speak_b:"HABLAR B", stop_translate:"DETENER Y TRADUCIR", translating:"Traduciendo...", select_langs:"Seleccionar idiomas y pulsar", trial_banner:"✦ Gratis por", days:"días", day:"día" },
  it: { translate:"TRADUCI", transcribe:"TRASCRIVI", speak:"PARLA", notes:"NOTE", meeting:"RIUNIONE", school:"SCUOLA", convo:"CONVO", reminders:"PROMEMORIA", settings:"Impostazioni", lang_pick:"Scegli lingua",
    rec_lang:"Lingua di registrazione", subject:"Materia", start_rec:"INIZIA REGISTRAZIONE", stop_rec:"FERMA REGISTRAZIONE", cont_rec:"CONTINUA", recording:"● Registrazione...", analyze:"Analizza", copy:"Copia", copied:"Copiato!", export:"Esporta", ai_summary:"Riepilogo IA", analyzing:"Analisi...", select_lang:"Scegli lingua e registra", transcript_lbl:"Trascrizione", press_start:"Premi per iniziare", no_reminder:"Nessun promemoria. Aggiungi il primo!", what_todo:"Cosa bisogna fare?", text_mode:"Testo", voice_mode:"Voce", rec_voice:"Registra messaggio vocale", stop_voice:"Ferma", person_a:"Persona A", person_b:"Persona B", speak_a:"PARLA A", speak_b:"PARLA B", stop_translate:"FERMA E TRADUCI", translating:"Traduco...", select_langs:"Scegli le lingue e premi il pulsante", trial_banner:"✦ Gratis ancora", days:"giorni", day:"giorno" },
  pt: { translate:"TRADUZIR", transcribe:"TRANSCREVER", speak:"FALAR", notes:"NOTAS", meeting:"REUNIÃO", school:"ESCOLA", convo:"CONV", reminders:"LEMBRAR", settings:"Configurações", lang_pick:"Escolher idioma",
    rec_lang:"Idioma de gravação", subject:"Matéria", start_rec:"INICIAR GRAVAÇÃO", stop_rec:"PARAR GRAVAÇÃO", cont_rec:"CONTINUAR", recording:"● Gravando...", analyze:"Analisar", copy:"Copiar", copied:"Copiado!", export:"Exportar", ai_summary:"Resumo IA", analyzing:"Analisando...", select_lang:"Selecionar idioma e gravar", transcript_lbl:"Transcrição", press_start:"Pressionar para começar", no_reminder:"Sem lembretes. Adicione o primeiro!", what_todo:"O que precisa ser feito?", text_mode:"Texto", voice_mode:"Voz", rec_voice:"Gravar mensagem de voz", stop_voice:"Parar", person_a:"Pessoa A", person_b:"Pessoa B", speak_a:"FALAR A", speak_b:"FALAR B", stop_translate:"PARAR E TRADUZIR", translating:"Traduzindo...", select_langs:"Selecionar idiomas e pressionar", trial_banner:"✦ Grátis por", days:"dias", day:"dia" },
  nl: { translate:"VERTALEN", transcribe:"TRANSCRIPTIE", speak:"SPREKEN", notes:"NOTITIES", meeting:"VERGADER", school:"SCHOOL", convo:"GESPREK", reminders:"HERINNER", settings:"Instellingen", lang_pick:"Kies taal",
    rec_lang:"Opnametaal", subject:"Vak", start_rec:"OPNAME STARTEN", stop_rec:"OPNAME STOPPEN", cont_rec:"DOORGAAN", recording:"● Opname...", analyze:"Analyseer", copy:"Kopieer", copied:"Gekopieerd!", export:"Exporteer", ai_summary:"AI Samenvatting", analyzing:"Analyseer...", select_lang:"Kies taal en neem op", transcript_lbl:"Transcript", press_start:"Druk om te starten", no_reminder:"Geen herinneringen. Voeg eerste toe!", what_todo:"Wat moet er gedaan worden?", text_mode:"Tekst", voice_mode:"Spraak", rec_voice:"Spraakbericht opnemen", stop_voice:"Stoppen", person_a:"Persoon A", person_b:"Persoon B", speak_a:"SPREEK A", speak_b:"SPREEK B", stop_translate:"STOPPEN & VERTALEN", translating:"Vertalen...", select_langs:"Kies talen en druk op knop", trial_banner:"✦ Gratis nog", days:"dagen", day:"dag" },
  el: { translate:"ΜΕΤΑΦΡΑΣΗ", transcribe:"ΜΕΤΑΓΡΑΦΗ", speak:"ΜΙΛΑ", notes:"ΣΗΜΕΙΩΣΕΙΣ", meeting:"ΣΥΝΑΝΤΗΣΗ", school:"ΣΧΟΛΕΙΟ", convo:"ΣΥΝΟΜΙΛΙΑ", reminders:"ΥΠΕΝΘΥΜΙΣΗ", settings:"Ρυθμίσεις", lang_pick:"Επιλογή γλώσσας",
    rec_lang:"Γλώσσα εγγραφής", subject:"Μάθημα", start_rec:"ΕΝΑΡΞΗ ΕΓΓΡΑΦΗΣ", stop_rec:"ΔΙΑΚΟΠΗ ΕΓΓΡΑΦΗΣ", cont_rec:"ΣΥΝΕΧΕΙΑ", recording:"● Εγγραφή...", analyze:"Ανάλυση", copy:"Αντιγραφή", copied:"Αντιγράφηκε!", export:"Εξαγωγή", ai_summary:"AI Περίληψη", analyzing:"Ανάλυση...", select_lang:"Επιλέξτε γλώσσα και εγγράψτε", transcript_lbl:"Αντίγραφο", press_start:"Πατήστε για έναρξη", no_reminder:"Δεν υπάρχουν υπενθυμίσεις!", what_todo:"Τι χρειάζεται να γίνει;", text_mode:"Κείμενο", voice_mode:"Φωνή", rec_voice:"Ηχογράφηση φωνητικού", stop_voice:"Διακοπή", person_a:"Άτομο Α", person_b:"Άτομο Β", speak_a:"ΜΙΛΑ Α", speak_b:"ΜΙΛΑ Β", stop_translate:"ΔΙΑΚΟΠΗ & ΜΕΤΑΦΡΑΣΗ", translating:"Μετάφραση...", select_langs:"Επιλέξτε γλώσσες και πατήστε", trial_banner:"✦ Δωρεάν ακόμα", days:"ημέρες", day:"ημέρα" },
  sv: { translate:"ÖVERSÄTT", transcribe:"TRANSKRIBERA", speak:"TALA", notes:"ANTECKNINGAR", meeting:"MÖTE", school:"SKOLA", convo:"KONV", reminders:"PÅMINN", settings:"Inställningar", lang_pick:"Välj språk",
    rec_lang:"Inspelningsspråk", subject:"Ämne", start_rec:"BÖRJA SPELA IN", stop_rec:"STOPPA INSPELNING", cont_rec:"FORTSÄTT", recording:"● Spelar in...", analyze:"Analysera", copy:"Kopiera", copied:"Kopierat!", export:"Exportera", ai_summary:"AI Sammanfattning", analyzing:"Analyserar...", select_lang:"Välj språk och tryck spela in", transcript_lbl:"Transkription", press_start:"Tryck för att börja", no_reminder:"Inga påminnelser. Lägg till den första!", what_todo:"Vad behöver göras?", text_mode:"Text", voice_mode:"Röst", rec_voice:"Spela in röstmeddelande", stop_voice:"Stoppa", person_a:"Person A", person_b:"Person B", speak_a:"TALA A", speak_b:"TALA B", stop_translate:"STOPPA & ÖVERSÄTT", translating:"Översätter...", select_langs:"Välj språk och tryck på knappen nedan", trial_banner:"✦ Gratis i", days:"dagar", day:"dag" },
  no: { translate:"OVERSETT", transcribe:"TRANSKRIPSJON", speak:"SNAKK", notes:"NOTATER", meeting:"MØTE", school:"SKOLE", convo:"SAMTALE", reminders:"PÅMINN", settings:"Innstillinger", lang_pick:"Velg språk",
    rec_lang:"Opptaksspråk", subject:"Fag", start_rec:"START OPPTAK", stop_rec:"STOPP OPPTAK", cont_rec:"FORTSETT", recording:"● Tar opp...", analyze:"Analyser", copy:"Kopier", copied:"Kopiert!", export:"Eksporter", ai_summary:"AI Sammendrag", analyzing:"Analyserer...", select_lang:"Velg språk og trykk ta opp", transcript_lbl:"Transkripsjon", press_start:"Trykk for å starte", no_reminder:"Ingen påminnelser. Legg til den første!", what_todo:"Hva må gjøres?", text_mode:"Tekst", voice_mode:"Stemme", rec_voice:"Ta opp talemelding", stop_voice:"Stopp", person_a:"Person A", person_b:"Person B", speak_a:"SNAKK A", speak_b:"SNAKK B", stop_translate:"STOPP & OVERSETT", translating:"Oversetter...", select_langs:"Velg språk og trykk knappen nedenfor", trial_banner:"✦ Gratis i", days:"dager", day:"dag" },
  da: { translate:"OVERSÆT", transcribe:"TRANSSKRIPTION", speak:"TAL", notes:"NOTER", meeting:"MØDE", school:"SKOLE", convo:"SAMTALE", reminders:"PÅMIND", settings:"Indstillinger", lang_pick:"Vælg sprog",
    rec_lang:"Optagelsessprog", subject:"Fag", start_rec:"START OPTAGELSE", stop_rec:"STOP OPTAGELSE", cont_rec:"FORTSÆT", recording:"● Optager...", analyze:"Analyser", copy:"Kopiér", copied:"Kopieret!", export:"Eksportér", ai_summary:"AI Resumé", analyzing:"Analyserer...", select_lang:"Vælg sprog og tryk optag", transcript_lbl:"Transskription", press_start:"Tryk for at starte", no_reminder:"Ingen påmindelser. Tilføj den første!", what_todo:"Hvad skal der gøres?", text_mode:"Tekst", voice_mode:"Stemme", rec_voice:"Optag talebesked", stop_voice:"Stop", person_a:"Person A", person_b:"Person B", speak_a:"TAL A", speak_b:"TAL B", stop_translate:"STOP & OVERSÆT", translating:"Oversætter...", select_langs:"Vælg sprog og tryk på knappen nedenfor", trial_banner:"✦ Gratis i", days:"dage", day:"dag" },
  fi: { translate:"KÄÄNNÄ", transcribe:"TRANSKRIPTIO", speak:"PUHU", notes:"MUISTIINPANOT", meeting:"KOKOUS", school:"KOULU", convo:"KESKUSTELU", reminders:"MUISTUTUS", settings:"Asetukset", lang_pick:"Valitse kieli",
    rec_lang:"Tallennuskieli", subject:"Aihe", start_rec:"ALOITA TALLENNUS", stop_rec:"LOPETA TALLENNUS", cont_rec:"JATKA", recording:"● Tallennetaan...", analyze:"Analysoi", copy:"Kopioi", copied:"Kopioitu!", export:"Vie", ai_summary:"AI Yhteenveto", analyzing:"Analysoidaan...", select_lang:"Valitse kieli ja paina tallenna", transcript_lbl:"Transkriptio", press_start:"Paina aloittaaksesi", no_reminder:"Ei muistutuksia. Lisää ensimmäinen!", what_todo:"Mitä pitää tehdä?", text_mode:"Teksti", voice_mode:"Ääni", rec_voice:"Tallenna ääniviesti", stop_voice:"Lopeta", person_a:"Henkilö A", person_b:"Henkilö B", speak_a:"PUHU A", speak_b:"PUHU B", stop_translate:"LOPETA & KÄÄNNÄ", translating:"Käännetään...", select_langs:"Valitse kielet ja paina alla olevaa nappia", trial_banner:"✦ Ilmainen vielä", days:"päivää", day:"päivä" },
  pl: { translate:"TŁUMACZ", transcribe:"TRANSKRYPCJA", speak:"MÓWIĆ", notes:"NOTATKI", meeting:"SPOTKANIE", school:"SZKOŁA", convo:"ROZMOWA", reminders:"PRZYPOMNIJ", settings:"Ustawienia", lang_pick:"Wybierz język",
    rec_lang:"Język nagrania", subject:"Przedmiot", start_rec:"ZACZNIJ NAGRANIE", stop_rec:"ZATRZYMAJ NAGRANIE", cont_rec:"KONTYNUUJ", recording:"● Nagrywam...", analyze:"Analizuj", copy:"Kopiuj", copied:"Skopiowano!", export:"Eksportuj", ai_summary:"Podsumowanie AI", analyzing:"Analizuję...", select_lang:"Wybierz język i naciśnij nagraj", transcript_lbl:"Transkrypcja", press_start:"Naciśnij aby rozpocząć", no_reminder:"Brak przypomnień. Dodaj pierwsze!", what_todo:"Co należy zrobić?", text_mode:"Tekst", voice_mode:"Głos", rec_voice:"Nagraj wiadomość głosową", stop_voice:"Zatrzymaj", person_a:"Osoba A", person_b:"Osoba B", speak_a:"MÓW A", speak_b:"MÓW B", stop_translate:"ZATRZYMAJ I PRZETŁUMACZ", translating:"Tłumaczę...", select_langs:"Wybierz języki i naciśnij przycisk poniżej", trial_banner:"✦ Bezpłatnie jeszcze", days:"dni", day:"dzień" },
  cs: { translate:"PŘELOŽIT", transcribe:"PŘEPIS", speak:"MLUVIT", notes:"POZNÁMKY", meeting:"SCHŮZKA", school:"ŠKOLA", convo:"KONVERZACE", reminders:"PŘIPOMÍNKA", settings:"Nastavení", lang_pick:"Vybrat jazyk",
    rec_lang:"Jazyk nahrávání", subject:"Předmět", start_rec:"ZAČÍT NAHRÁVÁNÍ", stop_rec:"ZASTAVIT NAHRÁVÁNÍ", cont_rec:"POKRAČOVAT", recording:"● Nahrávám...", analyze:"Analyzovat", copy:"Kopírovat", copied:"Zkopírováno!", export:"Exportovat", ai_summary:"AI Shrnutí", analyzing:"Analyzuji...", select_lang:"Vyberte jazyk a nahrávejte", transcript_lbl:"Přepis", press_start:"Stiskněte pro spuštění", no_reminder:"Žádné připomínky. Přidejte první!", what_todo:"Co je třeba udělat?", text_mode:"Text", voice_mode:"Hlas", rec_voice:"Nahrát hlasovou zprávu", stop_voice:"Zastavit", person_a:"Osoba A", person_b:"Osoba B", speak_a:"MLUVIT A", speak_b:"MLUVIT B", stop_translate:"ZASTAVIT A PŘELOŽIT", translating:"Překládám...", select_langs:"Vyberte jazyky a stiskněte tlačítko níže", trial_banner:"✦ Zdarma ještě", days:"dní", day:"den" },
  sk: { translate:"PRELOŽIŤ", transcribe:"PREPIS", speak:"HOVORTE", notes:"POZNÁMKY", meeting:"STRETNUTIE", school:"ŠKOLA", convo:"KONVERZÁCIA", reminders:"PRIPOMIENKA", settings:"Nastavenia", lang_pick:"Vybrať jazyk",
    rec_lang:"Jazyk nahrávania", subject:"Predmet", start_rec:"ZAČAŤ NAHRÁVANIE", stop_rec:"ZASTAVIŤ NAHRÁVANIE", cont_rec:"POKRAČOVAŤ", recording:"● Nahrávam...", analyze:"Analyzovať", copy:"Kopírovať", copied:"Skopírované!", export:"Exportovať", ai_summary:"AI Zhrnutie", analyzing:"Analyzujem...", select_lang:"Vyberte jazyk a nahrajte", transcript_lbl:"Prepis", press_start:"Stlačte pre spustenie", no_reminder:"Žiadne pripomienky. Pridajte prvú!", what_todo:"Čo treba urobiť?", text_mode:"Text", voice_mode:"Hlas", rec_voice:"Nahrať hlasovú správu", stop_voice:"Zastaviť", person_a:"Osoba A", person_b:"Osoba B", speak_a:"HOVORTE A", speak_b:"HOVORTE B", stop_translate:"ZASTAVIŤ A PRELOŽIŤ", translating:"Prekladám...", select_langs:"Vyberte jazyky a stlačte tlačidlo nižšie", trial_banner:"✦ Zadarmo ešte", days:"dní", day:"deň" },
  hu: { translate:"FORDÍTÁS", transcribe:"ÁTÍRÁS", speak:"BESZÉLJ", notes:"JEGYZETEK", meeting:"MEGBESZÉLÉS", school:"ISKOLA", convo:"TÁRSALGÁS", reminders:"EMLÉKEZTETŐ", settings:"Beállítások", lang_pick:"Válasszon nyelvet",
    rec_lang:"Felvételi nyelv", subject:"Tantárgy", start_rec:"FELVÉTEL INDÍTÁSA", stop_rec:"FELVÉTEL LEÁLLÍTÁSA", cont_rec:"FOLYTATÁS", recording:"● Felvétel...", analyze:"Elemzés", copy:"Másolás", copied:"Másolva!", export:"Exportálás", ai_summary:"AI Összefoglaló", analyzing:"Elemzés...", select_lang:"Válasszon nyelvet és vegyen fel", transcript_lbl:"Átírás", press_start:"Nyomja meg a kezdéshez", no_reminder:"Nincs emlékeztető. Adja hozzá az elsőt!", what_todo:"Mit kell tenni?", text_mode:"Szöveg", voice_mode:"Hang", rec_voice:"Hangüzenet rögzítése", stop_voice:"Megállítás", person_a:"A személy", person_b:"B személy", speak_a:"BESZÉLJ A", speak_b:"BESZÉLJ B", stop_translate:"MEGÁLLÍTÁS & FORDÍTÁS", translating:"Fordítás...", select_langs:"Válasszon nyelveket és nyomja meg az alatti gombot", trial_banner:"✦ Ingyenes még", days:"nap", day:"nap" },
  ro: { translate:"TRADUCE", transcribe:"TRANSCRIERE", speak:"VORBEȘTE", notes:"NOTE", meeting:"ÎNTÂLNIRE", school:"ȘCOALĂ", convo:"CONVERSAȚIE", reminders:"REMINDER", settings:"Setări", lang_pick:"Alege limba",
    rec_lang:"Limba de înregistrare", subject:"Subiect", start_rec:"ÎNCEPE ÎNREGISTRAREA", stop_rec:"OPREȘTE ÎNREGISTRAREA", cont_rec:"CONTINUĂ", recording:"● Înregistrare...", analyze:"Analizează", copy:"Copiază", copied:"Copiat!", export:"Exportă", ai_summary:"Rezumat AI", analyzing:"Analizez...", select_lang:"Selectează limba și înregistrează", transcript_lbl:"Transcriere", press_start:"Apasă pentru a începe", no_reminder:"Fără mementouri. Adaugă primul!", what_todo:"Ce trebuie făcut?", text_mode:"Text", voice_mode:"Voce", rec_voice:"Înregistrează mesaj vocal", stop_voice:"Oprește", person_a:"Persoana A", person_b:"Persoana B", speak_a:"VORBEȘTE A", speak_b:"VORBEȘTE B", stop_translate:"OPREȘTE & TRADUCE", translating:"Traduc...", select_langs:"Selectează limbi și apasă butonul de mai jos", trial_banner:"✦ Gratuit încă", days:"zile", day:"zi" },
  bg: { translate:"ПРЕВОД", transcribe:"ТРАНСКРИПТ", speak:"ГОВОРИ", notes:"БЕЛЕЖКИ", meeting:"СРЕЩА", school:"УЧИЛИЩЕ", convo:"РАЗГОВОР", reminders:"НАПОМНЯНЕ", settings:"Настройки", lang_pick:"Избери език",
    rec_lang:"Език на запис", subject:"Предмет", start_rec:"ЗАПОЧНИ ЗАПИС", stop_rec:"СПРИ ЗАПИС", cont_rec:"ПРОДЪЛЖИ", recording:"● Записвам...", analyze:"Анализирай", copy:"Копирай", copied:"Копирано!", export:"Експортирай", ai_summary:"AI Резюме", analyzing:"Анализирам...", select_lang:"Избери език и запиши", transcript_lbl:"Транскрипт", press_start:"Натисни за начало", no_reminder:"Няма напомняния. Добави първото!", what_todo:"Какво трябва да се направи?", text_mode:"Текст", voice_mode:"Глас", rec_voice:"Запиши гласово съобщение", stop_voice:"Спри", person_a:"Лице А", person_b:"Лице Б", speak_a:"ГОВОРИ А", speak_b:"ГОВОРИ Б", stop_translate:"СПРИ & ПРЕВЕДИ", translating:"Превеждам...", select_langs:"Избери езици и натисни бутона по-долу", trial_banner:"✦ Безплатно още", days:"дни", day:"ден" },
  ru: { translate:"ПЕРЕВОД", transcribe:"ТРАНСКРИПТ", speak:"ГОВОРИТЬ", notes:"ЗАМЕТКИ", meeting:"МИТИНГ", school:"ШКОЛА", convo:"РАЗГОВОР", reminders:"НАПОМНИТЬ", settings:"Настройки", lang_pick:"Выбрать язык",
    rec_lang:"Язык записи", subject:"Предмет", start_rec:"НАЧАТЬ ЗАПИСЬ", stop_rec:"ОСТАНОВИТЬ ЗАПИСЬ", cont_rec:"ПРОДОЛЖИТЬ", recording:"● Запись...", analyze:"Анализировать", copy:"Копировать", copied:"Скопировано!", export:"Экспорт", ai_summary:"AI Резюме", analyzing:"Анализирую...", select_lang:"Выберите язык и запишите", transcript_lbl:"Транскрипт", press_start:"Нажмите для начала", no_reminder:"Нет напоминаний. Добавьте первое!", what_todo:"Что нужно сделать?", text_mode:"Текст", voice_mode:"Голос", rec_voice:"Записать голосовое сообщение", stop_voice:"Стоп", person_a:"Человек А", person_b:"Человек Б", speak_a:"ГОВОРИТЬ А", speak_b:"ГОВОРИТЬ Б", stop_translate:"СТОП & ПЕРЕВЕСТИ", translating:"Перевожу...", select_langs:"Выберите языки и нажмите кнопку ниже", trial_banner:"✦ Бесплатно ещё", days:"дней", day:"день" },
  uk: { translate:"ПЕРЕКЛАСТИ", transcribe:"ТРАНСКРИПТ", speak:"ГОВОРИТИ", notes:"НОТАТКИ", meeting:"ЗУСТРІЧ", school:"ШКОЛА", convo:"РОЗМОВА", reminders:"НАГАДАТИ", settings:"Налаштування", lang_pick:"Вибрати мову",
    rec_lang:"Мова запису", subject:"Предмет", start_rec:"ПОЧАТИ ЗАПИС", stop_rec:"ЗУПИНИТИ ЗАПИС", cont_rec:"ПРОДОВЖИТИ", recording:"● Запис...", analyze:"Аналізувати", copy:"Копіювати", copied:"Скопійовано!", export:"Експорт", ai_summary:"AI Резюме", analyzing:"Аналізую...", select_lang:"Виберіть мову та записуйте", transcript_lbl:"Транскрипт", press_start:"Натисніть для початку", no_reminder:"Немає нагадувань. Додайте перше!", what_todo:"Що потрібно зробити?", text_mode:"Текст", voice_mode:"Голос", rec_voice:"Записати голосове повідомлення", stop_voice:"Стоп", person_a:"Особа А", person_b:"Особа Б", speak_a:"ГОВОРИТИ А", speak_b:"ГОВОРИТИ Б", stop_translate:"СТОП & ПЕРЕКЛАСТИ", translating:"Перекладаю...", select_langs:"Виберіть мови та натисніть кнопку нижче", trial_banner:"✦ Безкоштовно ще", days:"днів", day:"день" },
  tr: { translate:"ÇEVİR", transcribe:"TRANSKRİPT", speak:"KONUŞ", notes:"NOTLAR", meeting:"TOPLANTI", school:"OKUL", convo:"KONUŞMA", reminders:"HATIRLA", settings:"Ayarlar", lang_pick:"Dil seç",
    rec_lang:"Kayıt dili", subject:"Ders", start_rec:"KAYDI BAŞLAT", stop_rec:"KAYDI DURDUR", cont_rec:"DEVAM ET", recording:"● Kaydediyorum...", analyze:"Analiz et", copy:"Kopyala", copied:"Kopyalandı!", export:"Dışa aktar", ai_summary:"AI Özeti", analyzing:"Analiz ediyorum...", select_lang:"Dil seç ve kaydet", transcript_lbl:"Transkript", press_start:"Başlamak için bas", no_reminder:"Hatırlatma yok. İlkini ekle!", what_todo:"Ne yapılması gerekiyor?", text_mode:"Metin", voice_mode:"Ses", rec_voice:"Sesli mesaj kaydet", stop_voice:"Durdur", person_a:"Kişi A", person_b:"Kişi B", speak_a:"KONUŞ A", speak_b:"KONUŞ B", stop_translate:"DURDUR VE ÇEVİR", translating:"Çeviriyorum...", select_langs:"Dilleri seç ve aşağıdaki düğmeye bas", trial_banner:"✦ Ücretsiz daha", days:"gün", day:"gün" },
  ar: { translate:"ترجمة", transcribe:"نسخ", speak:"تحدث", notes:"ملاحظات", meeting:"اجتماع", school:"مدرسة", convo:"محادثة", reminders:"تذكير", settings:"إعدادات", lang_pick:"اختر اللغة",
    rec_lang:"لغة التسجيل", subject:"المادة", start_rec:"ابدأ التسجيل", stop_rec:"أوقف التسجيل", cont_rec:"استمر", recording:"● جارٍ التسجيل...", analyze:"تحليل", copy:"نسخ", copied:"تم النسخ!", export:"تصدير", ai_summary:"ملخص الذكاء الاصطناعي", analyzing:"جارٍ التحليل...", select_lang:"اختر اللغة واضغط تسجيل", transcript_lbl:"النص", press_start:"اضغط للبدء", no_reminder:"لا توجد تذكيرات. أضف الأول!", what_todo:"ماذا يجب أن يُفعل؟", text_mode:"نص", voice_mode:"صوت", rec_voice:"تسجيل رسالة صوتية", stop_voice:"إيقاف", person_a:"الشخص أ", person_b:"الشخص ب", speak_a:"تحدث أ", speak_b:"تحدث ب", stop_translate:"أوقف وترجم", translating:"جارٍ الترجمة...", select_langs:"اختر اللغات واضغط الزر أدناه", trial_banner:"✦ مجانًا لمدة", days:"أيام", day:"يوم" },
  he: { translate:"תרגום", transcribe:"תמלול", speak:"דבר", notes:"הערות", meeting:"פגישה", school:"בית ספר", convo:"שיחה", reminders:"תזכורת", settings:"הגדרות", lang_pick:"בחר שפה",
    rec_lang:"שפת הקלטה", subject:"מקצוע", start_rec:"התחל הקלטה", stop_rec:"עצור הקלטה", cont_rec:"המשך", recording:"● מקליט...", analyze:"נתח", copy:"העתק", copied:"הועתק!", export:"ייצוא", ai_summary:"סיכום AI", analyzing:"מנתח...", select_lang:"בחר שפה ולחץ הקלט", transcript_lbl:"תמליל", press_start:"לחץ להתחלה", no_reminder:"אין תזכורות. הוסף את הראשונה!", what_todo:"מה צריך לעשות?", text_mode:"טקסט", voice_mode:"קול", rec_voice:"הקלט הודעה קולית", stop_voice:"עצור", person_a:"אדם א", person_b:"אדם ב", speak_a:"דבר א", speak_b:"דבר ב", stop_translate:"עצור ותרגם", translating:"מתרגם...", select_langs:"בחר שפות ולחץ על הכפתור למטה", trial_banner:"✦ חינם עוד", days:"ימים", day:"יום" },
  fa: { translate:"ترجمه", transcribe:"رونویسی", speak:"صحبت کن", notes:"یادداشت", meeting:"جلسه", school:"مدرسه", convo:"مکالمه", reminders:"یادآوری", settings:"تنظیمات", lang_pick:"انتخاب زبان",
    rec_lang:"زبان ضبط", subject:"موضوع", start_rec:"شروع ضبط", stop_rec:"توقف ضبط", cont_rec:"ادامه", recording:"● در حال ضبط...", analyze:"تحلیل", copy:"کپی", copied:"کپی شد!", export:"خروجی", ai_summary:"خلاصه هوش مصنوعی", analyzing:"در حال تحلیل...", select_lang:"زبان را انتخاب کنید و ضبط کنید", transcript_lbl:"رونوشت", press_start:"برای شروع فشار دهید", no_reminder:"یادآوری وجود ندارد. اولی را اضافه کنید!", what_todo:"چه باید انجام شود؟", text_mode:"متن", voice_mode:"صدا", rec_voice:"پیام صوتی ضبط کنید", stop_voice:"توقف", person_a:"شخص الف", person_b:"شخص ب", speak_a:"صحبت الف", speak_b:"صحبت ب", stop_translate:"توقف و ترجمه", translating:"در حال ترجمه...", select_langs:"زبان‌ها را انتخاب کنید و دکمه زیر را فشار دهید", trial_banner:"✦ رایگان تا", days:"روز", day:"روز" },
  zh: { translate:"翻译", transcribe:"转录", speak:"说话", notes:"笔记", meeting:"会议", school:"学校", convo:"对话", reminders:"提醒", settings:"设置", lang_pick:"选择语言",
    rec_lang:"录音语言", subject:"科目", start_rec:"开始录音", stop_rec:"停止录音", cont_rec:"继续", recording:"● 录音中...", analyze:"分析", copy:"复制", copied:"已复制!", export:"导出", ai_summary:"AI摘要", analyzing:"分析中...", select_lang:"选择语言并开始录音", transcript_lbl:"转录", press_start:"按下开始", no_reminder:"没有提醒。添加第一个!", what_todo:"需要做什么?", text_mode:"文字", voice_mode:"语音", rec_voice:"录制语音消息", stop_voice:"停止", person_a:"人A", person_b:"人B", speak_a:"说话A", speak_b:"说话B", stop_translate:"停止并翻译", translating:"翻译中...", select_langs:"选择语言并按下面的按钮", trial_banner:"✦ 免费还有", days:"天", day:"天" },
  ja: { translate:"翻訳", transcribe:"文字起こし", speak:"話す", notes:"メモ", meeting:"ミーティング", school:"学校", convo:"会話", reminders:"リマインダー", settings:"設定", lang_pick:"言語を選択",
    rec_lang:"録音言語", subject:"科目", start_rec:"録音開始", stop_rec:"録音停止", cont_rec:"続ける", recording:"● 録音中...", analyze:"分析", copy:"コピー", copied:"コピーしました!", export:"エクスポート", ai_summary:"AI要約", analyzing:"分析中...", select_lang:"言語を選択して録音", transcript_lbl:"文字起こし", press_start:"押して開始", no_reminder:"リマインダーなし。最初を追加!", what_todo:"何をすべきですか?", text_mode:"テキスト", voice_mode:"音声", rec_voice:"音声メッセージを録音", stop_voice:"停止", person_a:"人物A", person_b:"人物B", speak_a:"話すA", speak_b:"話すB", stop_translate:"停止して翻訳", translating:"翻訳中...", select_langs:"言語を選択して下のボタンを押す", trial_banner:"✦ あと無料", days:"日", day:"日" },
  ko: { translate:"번역", transcribe:"전사", speak:"말하기", notes:"메모", meeting:"회의", school:"학교", convo:"대화", reminders:"알림", settings:"설정", lang_pick:"언어 선택",
    rec_lang:"녹음 언어", subject:"과목", start_rec:"녹음 시작", stop_rec:"녹음 중지", cont_rec:"계속", recording:"● 녹음 중...", analyze:"분석", copy:"복사", copied:"복사됨!", export:"내보내기", ai_summary:"AI 요약", analyzing:"분석 중...", select_lang:"언어 선택 후 녹음", transcript_lbl:"전사", press_start:"시작하려면 누르세요", no_reminder:"알림 없음. 첫 번째 추가!", what_todo:"무엇을 해야 합니까?", text_mode:"텍스트", voice_mode:"음성", rec_voice:"음성 메시지 녹음", stop_voice:"정지", person_a:"사람 A", person_b:"사람 B", speak_a:"말하기 A", speak_b:"말하기 B", stop_translate:"정지 및 번역", translating:"번역 중...", select_langs:"언어를 선택하고 아래 버튼을 누르세요", trial_banner:"✦ 무료 앞으로", days:"일", day:"일" },
  hi: { translate:"अनुवाद", transcribe:"ट्रांसक्रिप्ट", speak:"बोलें", notes:"नोट्स", meeting:"बैठक", school:"स्कूल", convo:"बातचीत", reminders:"याद दिलाएं", settings:"सेटिंग्स", lang_pick:"भाषा चुनें",
    rec_lang:"रिकॉर्डिंग भाषा", subject:"विषय", start_rec:"रिकॉर्डिंग शुरू करें", stop_rec:"रिकॉर्डिंग रोकें", cont_rec:"जारी रखें", recording:"● रिकॉर्ड हो रहा है...", analyze:"विश्लेषण", copy:"कॉपी", copied:"कॉपी हो गया!", export:"निर्यात", ai_summary:"AI सारांश", analyzing:"विश्लेषण हो रहा है...", select_lang:"भाषा चुनें और रिकॉर्ड करें", transcript_lbl:"ट्रांसक्रिप्ट", press_start:"शुरू करने के लिए दबाएं", no_reminder:"कोई अनुस्मारक नहीं। पहला जोड़ें!", what_todo:"क्या करने की जरूरत है?", text_mode:"पाठ", voice_mode:"आवाज़", rec_voice:"वॉइस मैसेज रिकॉर्ड करें", stop_voice:"रोकें", person_a:"व्यक्ति A", person_b:"व्यक्ति B", speak_a:"बोलें A", speak_b:"बोलें B", stop_translate:"रोकें और अनुवाद करें", translating:"अनुवाद हो रहा है...", select_langs:"भाषाएं चुनें और नीचे बटन दबाएं", trial_banner:"✦ मुफ्त अभी भी", days:"दिन", day:"दिन" },
};

const AppLangContext = createContext(null);

export function AppLangProvider({ children }) {
  const [appLang, setAppLangState] = useState(() => localStorage.getItem("whisper_lang") || null);

  const setAppLang = (code) => {
    localStorage.setItem("whisper_lang", code);
    setAppLangState(code);
  };

  const t = TRANSLATIONS[appLang] || TRANSLATIONS["en"];
  const langObj = LANGUAGES.find(l => l.code === appLang) || null;

  return (
    <AppLangContext.Provider value={{ appLang, setAppLang, t, LANGUAGES, langObj }}>
      {children}
    </AppLangContext.Provider>
  );
}

export function useAppLang() {
  return useContext(AppLangContext);
}